class Result:
    ok="200"
    badRequest="400"
    created="201"
    undocumented="500"
class Category:
    add="#operations-categories-controller-addCategory .opblock-summary-control"
    get="#operations-categories-controller-getAll_1 .opblock-summary-control"
    deleteAll="#operations-categories-controller-deleteAll_1 .opblock-summary-control"
    update="#operations-categories-controller-updateCategory .opblock-summary-control"
    delete="#operations-categories-controller-deleteCategory .opblock-summary-path span"
class Product:
    getAll = "#operations-products-controller-getAll .opblock-summary-control"
    update="#operations-products-controller-updateProduct .opblock-summary-control"
    add="#operations-products-controller-addProduct .opblock-summary-control"
    deleteAll="#operations-products-controller-deleteAll .opblock-summary-control"
    getByQuery="#operations-products-controller-getByQueryProductResponse .opblock-summary-control"
    getByCategory="#operations-products-controller-getByCategoryProductResponse .opblock-summary-path span"
    delete="#operations-products-controller-deleteProduct .opblock-summary-path span"
class Write:
    addCategoryExample="{\"name\":\"example\"}"
    #addProductExaple="{\"description\":\"example\",\"image\":\"example\",\"price\":9.99,\"title\":\"example\",\"categoryId\":5}"
    body=".body-param__text"
    parameters=".parameters-col_description > input"
    queryExample="exaple"
